### ISSUE TITLE
Fix dates of birth of trainers in GymServiceImpl

### ISSUE THREAD

**Issue by matejos** [mseleng/Kodemon#186]
Parameters are YYYY, MM, DD, not YYYY, DD, MM.
ALSO MONTH PARAMETER IS NUMBERED FROM 0 (so December is 11, not 12, etc.)

**Comment by mseleng** [comment]
That's why it is better to use their constants, eg. `Calendar.JULY` etc. :smile:

**Comment by mseleng** [comment]
We better check all occurrences of that. Not in the GymServiceImpl
