### ISSUE TITLE
Add screenshots and some nice description in the wiki

### ISSUE THREAD

**Issue by mseleng** [mseleng/Kodemon#194]

**Comment by Ahimtar** [comment]
Wiki updated

**Comment by mseleng** [comment]
Nice! We leave this open until we get the styles updated, so you can then upload new screenshots

**Comment by marosseleng** [comment]
Also, check whether the informations in READMEs are correct (logins/passwords) and test the rest api, whether the example response is correct, please. When you finish, Create a PR, where you change the app version to 1.0.0. I think, we would be proud :smile: 
EDIT: It's enough to change in the parent pom.xml

**Comment by Ahimtar** [comment]
Done.
