### ISSUE TITLE
Result of fighting with pokemon could have own page

### ISSUE THREAD

**Issue by Ahimtar** [mseleng/Kodemon#206]
Having it on index looks weird:

https://ctrlv.cz/shots/2016/12/15/HylB.png

**Comment by mseleng** [comment]
Setting milestone to final-milestone. We need to focus on bugfixing and testing.

**Comment by Ahimtar** [comment]
Perhaps after catching a pokemon, it could only redirect you to the grass page instead of the home page? Seems like the most simple, yet logical solution.

**Comment by mseleng** [comment]
Yeah, sounds logically. Feel free to implement :smile:
