### ISSUE TITLE
Don't let user fight a gym he's already beaten

### ISSUE THREAD

**Issue by matejos** [mseleng/Kodemon#207]
- [x] deny UI attack
- [ ] deny URL attack

**Comment by mseleng** [comment]
What?
Isn't this already done?

**Comment by Ahimtar** [comment]
Deny UI doesn't work due to badges not being saved correctly. URL wasn't solved yet afaik.

**Comment by matejos** [comment]
Nope. I didn't have time to get to it yet, working on fixing UI attack at the moment (Michal attempted to fix it, but...)

**Comment by matejos** [comment]
More like doesn't work due to multiple errors...

**Comment by matejos** [comment]
Fixed

**Comment by mseleng** [comment]
UI also? @matejos

**Comment by matejos** [comment]
Yes, in da732462b37a528317035d064ebe49a1d687f85f
