### ISSUE TITLE
NullPointerException when editing URL id field

### ISSUE THREAD

**Issue by matejos** [mseleng/Kodemon#209]
for example "http://localhost:8080/pa165/fight/fightGym?id=70"
probably happening on multiple other methods

**Comment by mseleng** [comment]
I don't understand. What do you mean by editing?

**Comment by matejos** [comment]
I gave you an example bro 😄 notice the _id=**70**_    
more like "manually inputting out-of-bounds id"

**Comment by mseleng** [comment]
I see now.. I didn't get "editing" :D
