### ISSUE TITLE
Trainer detail returning 404 error

### ISSUE THREAD

**Issue by mseleng** [mseleng/Kodemon#222]
Steps to reproduce: 
1. Go to the list of Trainers.
2. If you click any Trainer, redirect to the detail page work.
3. In the address bar, try to open Trainer detail of some user that does not exist, eg.:
`http://localhost:8080/pa165/user/detail/SomebodyElse`
4. Banner showing that no such user exists is displayed (OK)
5. Now when I click to any user (that exists) I got 404 error

**Comment by mseleng** [comment]
It may be related to the fact that after I manually typed URL and got not found banner shown, URL stayed the same, eg.: 
`http://localhost:8080/pa165/user/detail/SomebodyElse`
instead of returning to the 
`http://localhost:8080/pa165/user/list`
And then, when I click any user, I got redirected to the following URL:
`http://localhost:8080/pa165/user/detail/detail/Brock`
Notice the double `/detail`

**Comment by Ahimtar** [comment]
"It may be related" :smile:

**Comment by mseleng** [comment]
Not necessarily :smile: It may be related to something else :smile:
