### ISSUE TITLE
Implement Facade layer interfaces and implementations.

### ISSUE THREAD

**Issue by matejos** [mseleng/Kodemon#33]
Everything that should happen in the system must be available through these interfaces (create entities, deleting them etc);
You must have at least 2 non-trivial business functions on Service Layer (the example project contains several of them). Service layer is not always just a place to delegate to DAO;

**Comment by mseleng** [comment]
- [ ] #62 
- [ ] #63
- [ ] #64

**Comment by Ahimtar** [comment]
Resolved
