### ISSUE TITLE
Other points about the Facade and Service layers

### ISSUE THREAD

**Issue by matejos** [mseleng/Kodemon#34]
- All the classes must be wired via dependency injection. Your service objects should obtain an instance of the EntityManager that way;
- All the facade interfaces must not reference entities, but Transfer Objects only;
- All service interfaces must reference only entities, not Data Transfer Objects;
- You can use Dozer framework to map entity instances to transfer objects. The mapping may be done on Facade Layer;
- Facade layer is used to drive transactions;
- Facade layer will use Service layer and Service layer will use DAO layer;

**Comment by mseleng** [comment]
Closing this, as every point is already clear and implemented in #77.
