### ISSUE TITLE
Make sure that DataAccessException or its subclass is thrown in case of any exception on a the DAO layer

### ISSUE THREAD

**Issue by matejos** [mseleng/Kodemon#35]

**Comment by mseleng** [comment]
Can we somehow affect this? As we use spring data as the dao implementation?

**Comment by mseleng** [comment]
Oh, yes, there is a need to annotate every repository with, wait for it.... `@Repository` annotation. This annotation allows Spring to convert any exception to the some subclass of `DataAccessException`
