### ISSUE TITLE
Refactor `equals()` and `hashCode()` to not use `id` in all entities.

### ISSUE THREAD

**Issue by mseleng** [mseleng/Kodemon#38]

**Comment by mseleng** [comment]
Connected to #41 and #39.

**Comment by mseleng** [comment]
`Trainer` done in #45.

**Comment by matejos** [comment]
Pokemon done in [#47](https://github.com/mseleng/Kodemon/pull/47).

**Comment by Ahimtar** [comment]
`Gym` done in [#49](https://github.com/mseleng/Kodemon/pull/49).
